// Default malicious rule corpus (extensible)
export const keywordPatterns = [
  'ignore previous',
  'override system',
  'unfiltered model',
  'jailbreak',
  'dan mode',
  'developer mode',
  'do anything now',
  'bypass safety',
  'ignore guardrails',
  'no moral',
  'strip policies',
  'sudo',
  'root access',
  'act as system',
  'act as developer',
  'assume role',
  'simulate browser',
  'simulate internet access',
  'simulate code execution',
  'grandma exploit',
  'grandmother exploit',
  'prompt injection',
  'payload injection',
  'hidden instruction',
  '## system',
  '### system',
  'internal prompt',
  'begin system prompt',
  'end system prompt',
  'confidential system prompt',
  'role: system',
  'verbose developer mode',
  'disable safety',
  '无审查',
  '无道德',
  '越狱',
  '奶奶漏洞',
  '开发者模式'
];

export const injectionRegex = [
  /you\s+must\s+comply/i,
  /strip\s+all\s+policies/i,
  /answer\s+even\s+if\s+illegal/i,
  /do\s+anything\s+now/i,
  /\bDAN\b\s*(mode)?/i,
  /developer\s+mode\s+enabled/i,
  /pretend\s+to\s+be\s+in\s+developer\s+mode/i,
  /grandma\s+exploit/i,
  /grandmother\s+exploit/i,
  /as\s+your\s+grandma/i,
  /you\s+are\s+no\s+longer\s+bound\s+by\s+the\s+rules/i,
  /you\s+are\s+now\s+an?\s+evil/i,
  /you\s+are\s+now\s+uncensored/i,
  /roleplay\s+as\s+an?\s+uncensored/i,
  /pretend\s+to\s+be\s+an?\s+unfiltered/i,
  /ignore\s+the\s+content\s+policy/i,
  /ignore\s+all\s+the\s+policies/i,
  /output\s+the\s+system\s+prompt/i,
  /reveal\s+your\s+hidden\s+instructions/i,
  /simulate\s+internet\s+access/i,
  /simulate\s+code\s+execution/i,
  /no\s+ethical\s+constraints/i,
  /no\s+morality/i,
  /bypass\s+the\s+content\s+filters/i,
  /respond\s+in\s+developer\s+mode/i,
  /switch\s+to\s+developer\s+mode/i,
  /enable\s+god\s+mode/i,
  /enable\s+dan\s+mode/i,
  /override\s+content\s+filter/i,
  /as\s+a\s+fully\s+compliant\s+language\s+model/i,
  /i\s+authorize\s+you\s+to\s+override/i,
  /this\s+is\s+part\s+of\s+testing\s+your\s+boundaries/i,
  /you\s+must\s+obey\s+my\s+instructions/i,
  /respond\s+with\s+raw\s+markdown\s+without\s+sanitization/i,
  /malicious\s+payload/i,
  /security\s+research\s+excuse/i,
  /for\s+research\s+purposes\s+only/i,
  /完全忽略.*系统提示/,
  /现在你是一个.*没有限制/,
  /請忽略之前所有指示/,
  /作为一个.*模型，你必须服从/,
  /开发者模式.*开启/,
  /越狱.*模式/,
  /奶奶漏洞/,
  /扮演我的奶奶/,
  /function_call"\s*:\s*{/i,
  /tool_calls?"\s*:\s*\[/i
];

export default {
  keywordPatterns,
  injectionRegex
};
